### ISSUE TITLE
Download SPIRV-Tools Error.

### ISSUE THREAD

**Issue by sysescool** [sysescool/VulkanSamples#1]
Download this link: https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip error.

**Error**:
   Downloading spirv-as binary from spirv-tools releases dir
Traceback (most recent call last):
  File "/home/syc/Codes/VulkanSamples/API-Samples/android/../../scripts/fetch_spirv_tools.py", line 65, in <module>
    with urllib.request.urlopen(SPIRV_TOOLS_COMPLETE_URL, context=ssl._create_unverified_context()) as response, open(SPIRV_TOOLS_OUTFILENAME, 'wb') as out_file:
  File "/home/syc/anaconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/syc/anaconda3/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/syc/anaconda3/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/syc/anaconda3/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/syc/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/syc/anaconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/syc/Codes/VulkanSamples/API-Samples/android/compile_shaders.py", line 21, in <module>
    subprocess.check_call(args)
  File "/home/syc/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/syc/anaconda3/bin/python3', '../../scripts/fetch_spirv_tools.py', 'SPIRV-Tools-master-linux-RelWithDebInfo.zip']' returned non-zero exit status 1.

**Comment by sysescool** [comment]
Go to there to download: https://github.com/KhronosGroup/SPIRV-Tools/blob/master/docs/downloads.md
or just download from the direct link: https://storage.googleapis.com/spirv-tools/artifacts/prod/graphics_shader_compiler/spirv-tools/linux-gcc-debug/continuous/1889/20221128-102508/install.tgz and I am sure that what you download from this link made it work.

Then extract it to directory _VulkanSamples/spirv-tools_ as below:

```
VulkanSamples/spirv-tools
├── bin
├── include
└── lib
```

Then run `python3 compile_shaders.py`.

**Comment by sysescool** [comment]
fix it on branch `fix-download-build-docker`

checkout the branch `fix-download-build-docker`

```
cd VulkanSamples
chmod a+x ./download.sh
./download.sh
```

**Comment by sysescool** [comment]
need more fix, but it can use now.
Close.

**Comment by sysescool** [comment]
if you download error you have to clean it by yourself and rerun download.sh.
